FQC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('management.urls')),
    path('account/',include('account.urls'),),
    path('social-auth/',include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views, api

app_name='management'


urlpatterns = [
    path('', views.index, name='index'),
    path('user-dashboard',views.user_dashboard,name='user_dashboard'),
    path('anonymous-complain',views.anonymous_complain,name='anonymous_complain'),
    path('all-complains',views.all_complains,name='all_complains'),
    path('create-complain',views.create_complain,name='create_complain'),
    path('complain-view/<int:id>',views.view_complain,name='view_complain'),
    path('category-list',views.category_list,name='category_list'),
    path('create-category',views.create_category,name='create_category'),
    path('create-category/<int:id>',views.create_category,name='edit_category'),
    path('create-sub-category',views.create_sub_category, name='create_sub_category'),
     path('edit-sub-category/<int:id>',views.create_sub_category, name='edit_sub_category'),
    path('delete-category/<int:id>',views.delete_category,name='delete_category'),
    path('delete-sub-category/<int:id>',views.delete_sub_category,name='delete_sub_category'),
    path('create-communication/<int:id>',views.create_communication,name='create_communication'),
    path('response/<int:id>',views.response, name="response"),
    path('management/complaint/<int:complain_id>', api.ComplainDetails.as_view(), name='complaint_details'),
    path('search',views.search_complain,name='search_complain'),
    path('create-FAQ', views.create_faq, name="create_faq"),
    path('faqs-list', views.all_faqs, name="all_faqs"),
    path('index-faqs', views.index_faq, name="index_faq"),
    path('index-categories', views.index_categories, name="index_categories"),
]

management/models.py
from django.db import models
from account.models import CustomUser
import hashlib
import shortuuid
from django.core.validators import FileExtensionValidator,MaxLengthValidator,MaxValueValidator
from .choices import status,purpose

# Create your models here.    
class ComplainCategory(models.Model):
    english_name=models.CharField(max_length=60,unique=True)
    nepali_name=models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return self.english_name

class ComplainSubCategory(models.Model):
    english_name=models.CharField(max_length=60,unique=True)
    nepali_name=models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.english_name



class AnonymousUser(models.Model):
    """Personal Information"""
    first_name=models.CharField(max_length=50,default='abc')
    last_name=models.CharField(max_length=50,null=True)
    phone_number=models.CharField(max_length=13)
    address=models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.first_name
class Complain(models.Model):
    ticket_no=models.CharField(max_length=22, unique=True)
    complain_category = models.ForeignKey(ComplainCategory,on_delete=models.CASCADE,related_name='related_complain',null=True)
    complain_sub_category=models.ForeignKey(ComplainSubCategory,on_delete=models.CASCADE,null=True,related_name='complain_sub_category')
    complain_title=models.CharField(max_length=300)
    complain_description=models.TextField()
    complain_image=models.ImageField()
    address=models.CharField(max_length=200,null=True)
    complain_status=models.PositiveBigIntegerField(choices=status,default=1)
    purpose=models.PositiveBigIntegerField(choices=purpose,default=None)
    is_anonymous=models.OneToOneField(AnonymousUser, null=True, on_delete=models.CASCADE)
    created_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,related_name='user_complains')
    
    assigned_by=models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,related_name='assigned_complain')
    assigned_to=models.ManyToManyField(CustomUser,related_name='is_available',default=None)
    assigned_date=models.DateTimeField(blank=True,null=True)
    created_date=models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return self.complain_title
    def save(self, *args, **kwargs):
        if not self.ticket_no:
            unique_id = shortuuid.uuid()
            complain_count=Complain.objects.count()
            digits_only = ''.join(filter(str.isdigit, unique_id))
            complain_category_id = self.complain_category.id if self.complain_category else 'NA'
            self.ticket_no = f'DFTQC-C{complain_category_id}-{str(complain_count)+digits_only[:4]}'

        super(Complain, self).save(*args, **kwargs)
    def get_status(self):
        if self.complain_status == 1:
            return 'Pending'
        elif self.complain_status == 3:
            return 'Responded'
        elif self.complain_status == 4:
            return "Rejected"
        else:
            return 'Processing'
        

    def get_purpose(self):
        if self.purpose == 1:
            return 'Export'
        elif self.purpose == 2:
            return 'Import'
        elif self.purpose == 3:
            return 'Domestic'
        elif self.purpose == 4:
            return 'Regulations'
        else:
            return 'Others'
    class Meta:
        ordering=['-id']
class Communication(models.Model):
    complain = models.ForeignKey(Complain,on_delete=models.CASCADE,related_name='complain_communication')
    communication_creator=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='creator',default=None)
    message=models.TextField(null=True)
    image=models.ImageField(null=True)

class Response(models.Model):
    created_by=models.ForeignKey(CustomUser,on_delete=models.SET_NULL,null=True)
    response_description=models.TextField()
    complain=models.ForeignKey(Complain,on_delete=models.CASCADE,related_name='response')
    response_image=models.ImageField(null=True)


class FAQ(models.Model):
    question=models.TextField()
    answer=models.TextField()
    

management/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import ComplainCategory,ComplainSubCategory,Complain, FAQ
from .choices import status,purpose

#Category and Broad category related Form
class ComplainCategoryForm(forms.ModelForm):
    class Meta:
        model=ComplainCategory
        fields=['english_name','nepali_name']
class ComplainSubCategoryForm(forms.ModelForm):
    class Meta:
        model=ComplainSubCategory
        fields='__all__'
class FAQForm(forms.ModelForm):
    class Meta:
        model=FAQ
        fields='__all__'
    

#Anonymous Form
class AnonymousForm(forms.Form):
    first_name=forms.CharField(max_length=50, required=True)
    last_name=forms.CharField(max_length=50, required=True)
    phone_number= forms.CharField(
        max_length=10,required=True,
        validators=[
            RegexValidator(r'^\d{10}$', 'Phone number must be 10 digits')
        ]
    )
    person_address=forms.CharField(max_length=60,required=True)
    complain_title= forms.CharField(max_length=200,required=True)
    complain_description= forms.CharField(max_length=2000,required=True)
    enquiry_address=forms.CharField(max_length=200,required=True)
    complain_image=forms.ImageField(required=False)

class ComplainForm(forms.ModelForm):
    class meta:
        fields=['broad_category', 'complain_title','complain_description','province','municipality','district']

management/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,get_list_or_404,redirect
from django.db.models import Count
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.utils import timezone
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from .models import ComplainCategory,ComplainSubCategory, AnonymousUser,Complain, Communication, Response, FAQ
from account.models import CustomUser
from .forms import AnonymousForm,ComplainCategoryForm,ComplainSubCategoryForm, FAQForm
from django.core.mail import send_mail
from django.template.loader import render_to_string
from account.decorators import authentication_not_required,is_admin,is_superadmin,is_user, is_employee
from django.contrib.auth.decorators import login_required
from .tasks import send_notification_mail
from .choices import purpose

# Create your views here.
def index(request):
    total_counts=Complain.objects.count()
    plant_health_count=Complain.objects.filter(complain_category__english_name='Plant Health').count()
    animal_health_count=Complain.objects.filter(complain_category__english_name='Animal Health').count()
    food_safety_count=Complain.objects.filter(complain_category__english_name='Food Safety').count()
    others_count=Complain.objects.filter(complain_category__english_name='Others').count()
    context={
        'total_counts':total_counts,
        'plant_health_count': plant_health_count,
        'animal_health_count':animal_health_count,
        'food_safety_count':food_safety_count,
        'others_count':others_count,

    }
    return render(request,'management/index.html',context)

def user_dashboard(request):
    user=request.user
    if user.role==3:
        total_complains=Complain.objects.filter(created_by=user).count()
        plant_health_count=Complain.objects.filter(Q(complain_category__english_name='Plant Health') &
                                                        Q(created_by=user)).count()
        animal_health_count=Complain.objects.filter(Q(complain_category__english_name='Animal Health') &
                                                           Q(created_by=user)).count()
        food_safety_count=Complain.objects.filter(Q(complain_category__english_name='Food Safety') &
                                           Q(created_by=user)).count()
        others_count=Complain.objects.filter(Q(complain_category__english_name='Others') &
                                             Q(created_by=user)).count()
        pending_complains_count=Complain.objects.filter(Q(complain_status=1) &
                                                        Q(created_by=user)).count()
        processing_complains_count=Complain.objects.filter(Q(complain_status=2) &
                                                           Q(created_by=user)).count()
        responded_complains_count=Complain.objects.filter(Q(complain_status=3) &
                                                          Q(created_by=user)).count()
        rejected_complains_count=Complain.objects.filter(Q(complain_status=4) &
                                                         Q(created_by=user)).count()
    else:
        total_complains=Complain.objects.count()
        plant_health_count=Complain.objects.filter(complain_category__english_name='Plant Health').count()
        animal_health_count=Complain.objects.filter(complain_category__english_name='Animal Health').count()
        food_safety_count=Complain.objects.filter(complain_category__english_name='Food Safety').count()
        others_count=Complain.objects.filter(complain_category__english_name='Others').count()
        pending_complains_count=Complain.objects.filter(complain_status=1).count()
        processing_complains_count=Complain.objects.filter(complain_status=2).count()
        responded_complains_count=Complain.objects.filter(complain_status=3).count()
        rejected_complains_count=Complain.objects.filter(complain_status=4).count()
    context={
        'total_complains':total_complains,
        'plant_health_count': plant_health_count,
        'animal_health_count':animal_health_count,
        'food_safety_count':food_safety_count,
        'others_count':others_count,
        'pending_complains_count':pending_complains_count,
        'processing_complains_count':processing_complains_count,
        'responded_complains_count':responded_complains_count,
        'rejected_complains_count':rejected_complains_count,

    }
    return render(request,'dashboard.html',context)

#Category and Broad category related Views.
def category_list(request):
    sub_categories=ComplainSubCategory.objects.all()
    categories = ComplainCategory.objects.all()
    context={
        'categories':categories,
        'sub_categories': sub_categories
    }
    return render(request,'management/category_list.html',context)
@is_superadmin
def create_category(request,id=None):
    sub_categories=ComplainSubCategory.objects.all()
    if id:
        category=ComplainCategory.objects.get(id=id)
    else:
        category=None
    if request.method =='POST':
        form=ComplainCategoryForm(request.POST)
        if id:
            #for editing Purpose
            category=ComplainCategory.objects.get(id=id)
            english_name=form.data['english_name']
            nepali_name= form.data['nepali_name']
            category.english_name=english_name
            category.nepali_name=nepali_name
            category.save()
            messages.info(request,"Category Updated Successfully")
            return redirect(reverse('management:category_list'))
        else:
            if form.is_valid():
                english_name=form.cleaned_data['english_name']
                nepali_name= form.cleaned_data['nepali_name']
                complain_category,created=ComplainCategory.objects.get_or_create(
                    english_name=english_name,
                    nepali_name=nepali_name,
                )
            
                return redirect('management:category_list')
            else:
                messages.error(request,"please fill the form correctly.")
                return redirect(reverse('management:create_category'))
    else:
        context={
            'sub_categories':sub_categories,
            'category':category,
        }
        return render(request,'management/add_category.html',context)
@is_superadmin
def create_sub_category(request,id=None):
    categories=ComplainCategory.objects.all()
    if id:
        sub_category=ComplainSubCategory.objects.get(id=id)
    else:
        sub_category=None
    context={
        'categories':categories,
        'sub_category':sub_category
    }
    if request.method=='POST':
        form=ComplainSubCategoryForm(request.POST)
        if id:
            sub_category=ComplainSubCategory.objects.get(id=id)
            english_name=form.data['english_name']
            nepali_name=form.data['nepali_name']
            sub_category.english_name=english_name
            sub_category.nepali_name=nepali_name
            sub_category.save()
            messages.info(request,"Sub Category has been Updated Successfully.")
            return redirect(reverse('management:category_list'))
        else:
            if form.is_valid():
                sub_category_name=form.cleaned_data['english_name']
                nepali_name=form.cleaned_data['nepali_name']
                ComplainSubCategory.objects.create(
                    english_name=sub_category_name,
                    nepali_name=nepali_name,
                )
                messages.info(request,"Sub Category has been created Successfully.")
                return redirect('management:category_list')
            else:
                messages.error(request,'Please fill all fields to create subcategory.')
                return redirect(reverse('management:add_subcategory'))
    else:
        return render(request,'management/add_subcategory.html',context)
@is_superadmin
def delete_category(request,id):
    category=ComplainCategory.objects.get(id=id)
    category.delete()
    messages.info(request,"Category has been deleted Successfully.")
    return redirect(reverse('management:category_list'))
@is_superadmin
def delete_sub_category(request,id):
    sub_category=ComplainSubCategory.objects.get(id=id)
    sub_category.delete()
    messages.info(request,"Sub Category has been deleted Successfully.")
    return redirect(reverse('management:category_list'))

#Anonymous Complain related views
def anonymous_complain(request):  
    complain_category=ComplainCategory.objects.all()
    complain_purpose=purpose
    context={
            'complain_category': complain_category,
            'complain_purpose':complain_purpose,
            } 
    if request.method == 'POST':
        form=AnonymousForm(request.POST,request.FILES)
        if form.is_valid():
            person_first_name=form.cleaned_data['first_name']
            person_last_name=form.cleaned_data['last_name']
            person_phone_number=form.cleaned_data['phone_number']
            person_address=form.cleaned_data['person_address']
            complain_title=form.cleaned_data['complain_title']
            address=form.cleaned_data['enquiry_address']
            
            enquiry_category=int(request.POST.get('complain_category',None))
            enquiry_object_instance=ComplainCategory.objects.get(id=enquiry_category)
            complain_description=form.cleaned_data['complain_description']
            complain_image=form.cleaned_data['complain_image']
            enquiry_purpose=int(request.POST.get('purpose',None))
            anonymous_object={
            "first_name":person_first_name,
            "last_name": person_last_name,
            "phone_number":person_phone_number,
            "address":person_address
            }
            complain={
                "complain_category":enquiry_object_instance,

management/templates/management/add_broadcategory.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
            <div class="col-md-9 my-profile-w-85">
                <section id="tab-content-container">
                    <div class="p-0">
                        <div class="row">
                            <div class="main-section-title">
                                <a href="" class="section-title"> Broad Categories > <span style="color: #7a7a7a; font-size: 18px;"><small>Broad Category > Create</small></span></a>
                            </div>
                            <hr class="main-section-hr">

                            <div class="tab-content mt-4" id="myTabContent">
                              {% if broad_category.id  %}
                                <form action="{% url 'management:edit_broad_category' id=broad_category.id %}" method="post">
                                    {% else %}
                                    <form action="{% url 'management:create_broad_category'%}" method="post">
                                        {% endif %}
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-5">
                                            <label for="" class="form-label cm">Category name in english</label>
                                            <input type="text" class="form-control cm" {% if broad_category.id %} value="{{  broad_category.english_name }}"{% endif %}
                                                placeholder="Enter category name in english" name="english_name">
                                        </div>
                                        <div class="col-md-5">
                                            <label for="" class="form-label cm">Category name in nepali</label>
                                            <input type="text" class="form-control cm" {% if broad_category.id %} value="{{  broad_category.nepali_name }}"{% endif %}
                                                placeholder="Enter category name in nepali" name="nepali_name">
                                        </div>
                                        <div class="col-md-2 d-flex align-items-end">
                                            <button type="submit" class="btn btn-primary w-100">
                                                {%if broad_category.id %}Update{% else %}Create{% endif %}</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>


                        
                    </div>
                </section>

            </div>
            {% endblock %}

management/templates/management/add_category.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
            <div class="col-md-9 my-profile-w-85">
                <section id="tab-content-container">
                    <div class="p-0">
                        <div class="row">
                            <div class="main-section-title">
                                <a href="" class="section-title">Categories > <span style="color: #7a7a7a; font-size: 18px;"><small>Broad Category > Create</small></span></a>
                            </div>
                            <hr class="main-section-hr">

                            <div class="tab-content mt-4" id="myTabContent">
                                {% if category.id %}
                                <form action="{%  url 'management:edit_category' id=category.id %}" method='post'>
                                    {% else %}
                                    <form action="{%  url 'management:create_category'%}" method='post'>
                                    {% endif %}
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <label for="" class="form-label cm">Category name in english</label>
                                            <input type="text" class="form-control cm"{% if category.id %} value="{{ category.english_name }}"{% endif %}
                                                placeholder="Enter category name in english" name="english_name">
                                        </div>
                                        <div class="col-md-6">
                                            <label for="" class="form-label cm">Category name in nepali</label>
                                            <input type="text" class="form-control cm"{% if category.id %} value="{{ category.nepali_name }}"{% endif %}
                                                placeholder="Enter category name in nepali" name="nepali_name">
                                        </div>
                                        
                                    </div>

                                    <div class="row justify-content-end">
                                        <div class="col-md-2 d-flex align-items-end">
                                            <button type="submit" class="btn btn-primary w-100">
                                                {% if category.id %}Update{% else %} Create{% endif %}</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>


                        
                    </div>
                </section>

            </div>
   {% endblock %}

management/templates/management/add_subcategory.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
            <div class="col-md-9 my-profile-w-85">

                <section id="tab-content-container">
                    <div class="p-0">
                        <div class="row">
                            <div class="main-section-title">
                                <a href="" class="section-title"> Sub Categories > <span style="color: #7a7a7a; font-size: 18px;"><small>Sub-category > Create</small></span></a>
                            </div>
                            <hr class="main-section-hr">

                            <div class="tab-content mt-4" id="myTabContent">
                                {% if sub_category.id %}
                                <form action="{% url 'management:edit_sub_category' id=sub_category.id %}" method="post">
                                    {% else %}
                                <form action="{% url 'management:create_sub_category'%}" method="post">
                                    {% endif %}
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-4">
                                            <label for="" class="form-label cm">Sub-category name in english</label>
                                            <input type="text" class="form-control cm"{% if sub_category.id %} value="{{ sub_category.english_name }}"{% endif %}
                                                placeholder="Enter category name in english" name="english_name">
                                        </div>
                                        <div class="col-md-4">
                                            <label for="" class="form-label cm">Sub-category name in nepali</label>
                                            <input type="text" class="form-control cm"{% if sub_category.id %} value="{{ sub_category.nepali_name }}"{% endif %}
                                                placeholder="Enter category name in nepali" name="nepali_name">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12 text-end">
                                            <button type="submit" class="btn btn-primary w-25">
                                                {% if sub_category.id %}Update{% else %}Create{% endif %}</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>


                        
                    </div>
                </section>

            </div>
 {% endblock %}

management/templates/management/communication.html

                                <div class="complain-detail-container mt-4">
                                    <div class="complain-details-title">Communication Log</div>
                                    {% for communication in complain.complain_communication.all %}
                                    {% if request.user != communication.communication_creator %}
                                        <div class="row">
                                            <div class="row flex-row mt-2 w-50 ">
                                                <div class="response-profile-image">
                                                    <img src="https://ui-avatars.com/api/?name={{ communication.communication_creator.first_name.0 }}+{{ communication.communication_creator.last_name.0 }}&amp;rounded=true&amp;background=FB802C&amp;color=ffffff&amp;size=50&amp;bold=true" alt="">
                                                </div>
                                                <p class="response-message">
                                                    {{ communication.message }}
                                                {% if communication.image %}
                                                 <a href="{{ communication.image.url }}" data-fancybox data-caption="Single image">
                                                    <img src="{{ communication.image.url }}" width="10%"/>
                                                </a>
                                            </p>
                                                {% endif %}
                                            </div>
                                        </div>
                                        {% else %}

                                        <div class="row justify-content-end">
                                            <div class="row mt-2 w-50 flex-row-reverse">
                                                <div class="response-profile-image">
                                                    <img src="https://ui-avatars.com/api/?name={{ communication.communication_creator.first_name.0 }}+{{ communication.communication_creator.last_name.0 }}&amp;rounded=true&amp;background=FB802C&amp;color=ffffff&amp;size=50&amp;bold=true" alt="">
                                                </div>
                                                <p class="response-message">
                                                   {{ communication.message }}
                                                   {% if communication.image %}
                                                    <a href="{{ communication.image.url }}" data-fancybox data-caption="Single image">
                                                        <img src="{{ communication.image.url }}" width="10%"/> 
                                                    </a>
                                                    {% endif %}
                                                </p>
                                            </div>
                                        </div>
                                        {% endif %}
                                        {% endfor %}
                                         {% if not complain.response.exists %}
                                        <form action="{%url 'management:create_communication' id=complain.id %}" method="post" enctype="multipart/form-data" style="background: #f4f5f6; padding: 14px; border-radius: 6px;">
                                            {% csrf_token %}
                                            <label for="" class="form-label cm data">Reply Message</label>
                                            <textarea type="text" class="form-control cm" placeholder="Enter response message"
                                                            name="communication_message" rows="3" required></textarea>

                                        <label for="" class="form-label cm mb-0 data mt-2">Attachment (if any)</label>
                                        <input type="file" class="form-control cm" placeholder="Enter payment voucher number" name="communication_image">
                                        <div class="col-md-12 text-end mt-2">
                                            <button type="submit" class="btn btn-primary">Reply</button>
                                        </div>
                                        </form>
                                        {%endif %}

                                </div>


management/templates/management/success.html
{% load static %}
{% include 'header.html' %}
<h1>Complain Submitted Successfully.</h1>
{% include 'footer.html' %}