FQC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('management.urls')),
    path('account/',include('account.urls'),),
    path('social-auth/',include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('login/',views.login_user, name='login'),
    path('signup/',views.signup, name='signup'),
    path('all-user',views.all_user,name='all_user'),
    path('admin_user',views.admin_users,name='admin_user'),
    path('create-admin',views.create_admin,name='create_admin'),
    path('edit-admin/<int:id>',views.edit_user,name='edit_user'),
    path('user/<int:id>',views.view_user,name='view_user'),
    path('user/delete-user/<int:id>',views.delete_user,name='delete_user'),
    path('change_password',views.change_password,name='change_password'),
    path('my-account',views.my_account, name='my_account'),
    path('logout/',views.logout_user, name='logout_user'),
]

management/urls.py
from django.urls import path
from . import views, api

app_name='management'


urlpatterns = [
    path('', views.index, name='index'),
    path('user-dashboard',views.user_dashboard,name='user_dashboard'),
    path('anonymous-complain',views.anonymous_complain,name='anonymous_complain'),
    path('all-complains',views.all_complains,name='all_complains'),
    path('create-complain',views.create_complain,name='create_complain'),
    path('complain-view/<int:id>',views.view_complain,name='view_complain'),
    path('category-list',views.category_list,name='category_list'),
    path('create-category',views.create_category,name='create_category'),
    path('create-category/<int:id>',views.create_category,name='edit_category'),
    path('create-sub-category',views.create_sub_category, name='create_sub_category'),
     path('edit-sub-category/<int:id>',views.create_sub_category, name='edit_sub_category'),
    path('delete-category/<int:id>',views.delete_category,name='delete_category'),
    path('delete-sub-category/<int:id>',views.delete_sub_category,name='delete_sub_category'),
    path('create-communication/<int:id>',views.create_communication,name='create_communication'),
    path('response/<int:id>',views.response, name="response"),
    path('management/complaint/<int:complain_id>', api.ComplainDetails.as_view(), name='complaint_details'),
    path('search',views.search_complain,name='search_complain'),
    path('create-FAQ', views.create_faq, name="create_faq"),
    path('faqs-list', views.all_faqs, name="all_faqs"),
    path('index-faqs', views.index_faq, name="index_faq"),
    path('index-categories', views.index_categories, name="index_categories"),
]

templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
       <div class="col-md-9 my-profile-w-85">
        <section id="tab-content-container">
          <div class="p-0">
              <div class="row">
                  <div class="main-section-title">
                      <a href="" class="section-title">Enquiries in Number</a>
                  </div>
                  <hr class="main-section-hr">

                  <div class="tab-content mt-4" id="myTabContent">
                          <div class="row row-cols-1 row-cols-md-5 g-4 count-card">
                            <div class="col">
                              <div class="card mb-3 h-100">
                                <div class="card-body">
                                  <h5 class="card-title">Plant Health <br><small class="text-secondary mt-1">( बनस्पति स्वाथ्य  )</small></h5>
                                  <h2 class="card-text text-primary">{{ plant_health_count }}</h2>
                                </div>
                              </div>
                            </div>  
                            <div class="col">
                              <div class="card mb-3 h-100">
                                <div class="card-body">
                                  <h5 class="card-title">Animal Health<br><small class="text-secondary mt-1">( पशु  स्वाथ्य )</small></h5>
                                  <h2 class="card-text text-primary">{{ animal_health_count }}</h2>
                                </div>
                              </div>
                            </div>  
                            <div class="col">
                              <div class="card mb-3 h-100">
                                <div class="card-body">
                                  <h5 class="card-title">Food Safety <br><small class="text-secondary mt-1">( खाद्य सुरक्षा )</small></h5>
                                  <h2 class="card-text text-primary">{{ food_safety_count}}</h2>
                                </div>
                              </div>
                            </div>    
                            <div class="col">
                              <div class="card mb-3 h-100">
                                <div class="card-body">
                                  <h5 class="card-title">Others <br><small class="text-secondary mt-1">( अन्य )</small> </h5>
                                  <h2 class="card-text text-primary">{{ others_count }}</h2>
                                </div>
                              </div>
                            </div>  
                          </div>
                  </div>
              </div>
          </div>
        </section>
        <section id="tab-content-container" class="mt-4">
            <div class="row p-0 m-0">
                <div class="col-md-6 ">
                    <div class="InvestmentChart kit-card-db chart-bg">
                        <h5>Complain in accordance to category</h5>
                        <div class="row d-flex" style="justify-content: space-between;">
                            <div class="col-md-5 chart-info-list">
                                <ul class="chart-list">
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #01b7f9;"></i>Plant Health</span> <span class="badge text-bg">{{ plant_health_count }}</span></li>
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #ff8110;"></i>Animal Health</span><span class="badge text-bg">{{ animal_health_count}}</span></li>
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #5281ce;"></i>Food Safety</span><span class="badge text-bg">{{ food_safety_count}}</span></li>
              
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #998ceb;"></i>Others</span> <span class="badge text-bg">{{ others_count}}</span></li>
                                </ul>
                            </div>
                            <div class="col-md-7" style="display: flex; justify-content: center; align-items: center;">
                                <canvas id="categoryChart" style="width: 200px!important; height: 200px!important;"></canvas>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="InvestmentChart kit-card-db chart-bg">
                        <h5>Complain in accordance to Status</h5>
                        <div class="row d-flex" style="justify-content: space-between;">
                            <div class="col-md-5 chart-info-list">
                                <ul class="chart-list">
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #00c853;"></i>Responded</span><span class="badge text-bg">{{ responded_complains_count }}</span></li>
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #ffc107;"></i>Processing</span><span class="badge text-bg">{{ processing_complains_count }}</span></li>
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #673ab7;"></i>Pending</span><span class="badge text-bg">{{ pending_complains_count }}</span></li>
                                    <li><span><i class="fa-solid fa-circle me-2" style="color: #c62828;"></i>Rejected</span> <span class="badge text-bg">{{ rejected_complains_count }}</span></li>
                                </ul>
                            </div>
                            <div class="col-md-7" style="display: flex; justify-content: center; align-items: center;">
                                <canvas id="statusChart" style="width: 200px!important; height: 200px!important;"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
      var xValues = ["Plant Health", "Animal Health ", "Food Safety", "Others"];
      var yValues = [{{ plant_health_count }}, {{ animal_health_count }}, {{ food_safety_count }}, {{ others_count}}];
      var barColors = [
        "#01b7f9",
        "#ff8110",
        "#5281ce",
        "#9ef5ff"
      ];
    
      new Chart("categoryChart", {
        type: "pie",
        data: {
        //   labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          legend: {
            labels: {
              fontFamily: "Poppins, sans-serif"
            }
          },
          title: {
            display: false,
            text: "Investment",
            fontFamily: "Poppins, sans-serif"
          },
          tooltips: {
            titleFontFamily: "Poppins, sans-serif",
            bodyFontFamily: "Poppins, sans-serif"
          }
        }
      });
    </script>

<script>
    var xValues = ["Responded", "Pending", "Processing", "Rejected"];
    var yValues = [{{ responded_complains_count }}, {{ pending_complains_count }}, {{ processing_complains_count}}, {{rejected_complains_count}}];
    var barColors = [
      "#00c853",
      "#673ab7",
      "#ffc107",
      "#c62828"
    ];
  
    new Chart("statusChart", {
      type: "pie",
      data: {
      //   labels: xValues,
        datasets: [{
          backgroundColor: barColors,
          data: yValues
        }]
      },
      options: {
        legend: {
          labels: {
            fontFamily: "Poppins, sans-serif"
          }
        },
        title: {
          display: false,
          text: "Investment",
          fontFamily: "Poppins, sans-serif"
        },
        tooltips: {
          titleFontFamily: "Poppins, sans-serif",
          bodyFontFamily: "Poppins, sans-serif"
        }
      }
    });
  </script>
  {% endblock %}

templates/footer.html
{% block content %}
{% endblock %}
<div class="modal fade" id="navsearchBox" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="navsearchBoxLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered confirmation-modal">
    <div class="modal-content">
    <form method="post" action="{% url 'management:search_complain' %}">
      {% csrf_token %}
      <div class="modal-body delete-body text-start p-5">
        <label for="" class="form-label mb-1 data cm">Enquiry Token Number( टोकन नं. )</label>
        <input type="text" class="form-control cm" placeholder="Eg. DFTQC-CX-XXXX" name="search">
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <div class="row d-flex">
          <div class="col-md-12 d-flex justify-content-center">
            <button type="button" class="btn btn-primary cancel" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary ms-3">Search</button>
          </div>
        </div>
      </div>
    </form>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"
integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA=="
crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/header.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DFTQC | Grievance Handling System</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css"
    integrity="sha512-nNlU0WK2QfKsuEmdcTwkeh+lhGs6uyOxuUs+n+0oXSYDok5qy0EI0lt01ZynHq6+p/tbgpZ7P+yUb+r71wqdXg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  <div class="navbar navbar-expand-lg bg-body-tertiary" style="box-shadow: none;">
    <div class="container d-flex justify-space-between">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/nepal-government.png' %}" alt="Logo" class="d-inline-block align-text-top" style="width: 100px;">
      </a>
      <div class="navbar-brand text-center">
        <div>
          <p class="mb-0">Government of Nepal <br>
            Ministry of Agriculture and Livestock Development
          </p>
          <p class="mb-0 dftqc">Department of Food Technology and Quality Control <br> <span>SPS Enquiry Sewa Portal</span>
          </p>
        </div>
      </div>
      <div class="db-user-profile">
        <img src="{% static 'images/nepalflag.gif'%}" alt=""
          style="border-radius: 0; height: 80px;">
      </div>
    </div>
  </div>
  
  <div class="container-fluid public-nav sticky-top">
    <div class="container h-100">
      <nav class="navbar navbar-expand-lg h-100" style="box-shadow: none;">
        <div class="container-fluid public-nav-mbl">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <a class="nav-link register-btn mbl-display" href="{% url 'account:login'%}">Enquiry </a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown" style="height: 60px;">
            <ul class="navbar-nav h-100"
              style="width: 50%; justify-content: space-between; align-items: center;">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'management:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:index_categories' %}">Enquiry Categories</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#navsearchBox">Search Enquiry</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Manual</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'management:index_faq'%}">FAQs</a>
              </li>
            </ul>
            <div class="auth-btn ms-auto">
              <ul class="navbar-nav align-items-center">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'account:login'%}">Login</a>
                </li>
                <li class="nav-item ms-2">
                  <a class="nav-link register-btn" href="{% url 'account:signup'%}">Register</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </div>

templates/layout.html
{% extends 'login_footer.html' %}
{% block layout %}
{% load static %}
{% include 'login_header.html' %}
<div class="container-fluid px-4 mt-4">
    <div class="row">
       {% include 'navbar.html' %}
       {% block content %}
       {% endblock %}
    </div>
</div>
{% endblock %}

templates/login_footer.html
{% block layout %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
            $(document).ready(function() {
                 $('.multiple-group').select2();
            });
        </script> {% endcomment %}
    {% block scripts %}
    {% endblock %}
  </body>
</html>

templates/login_header.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DFTQC | Grievance Handling System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css" integrity="sha512-nNlU0WK2QfKsuEmdcTwkeh+lhGs6uyOxuUs+n+0oXSYDok5qy0EI0lt01ZynHq6+p/tbgpZ7P+yUb+r71wqdXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />   
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" /> {% endcomment %}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid d-flex justify-space-between mx-5">
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/np.png' %}" alt="Logo" width="14%" height="100%" class="d-inline-block align-text-top">
                <div class="ms-2">
                    <p class="mb-0">Government of Nepal <br>
                       Ministry of Agriculture and Livestock Development
                    </p>
                    <p class="mb-0 dftqc">Department of Food Technology and Quality Control <br> <span>SPS Enquiry Sewa Portal</span></p> 
                </div>
            </a>

            <div class="db-user-profile">
                <div class="db-user-profile-right dropdown main">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="usersmimage-div">
                            <img src="https://ui-avatars.com/api/?name={{ request.user.first_name.0 }}+{{ request.user.last_name.0 }}&amp;rounded=true&amp;background=FB802C&amp;color=ffffff&amp;size=28&amp;bold=true" alt=""></div>
                        <div>
                            <h3 class="username"> {{ request.user.first_name }} {{ request.user.last_name }}</h3>
                            <p class="userrole">{{ request.user.role_name }}</p>
                        </div>
                    </button>
                    <ul class="dropdown-menu ">
                        <li><a class="dropdown-item profile" href="{% url 'account:my_account'%}">My Account</a></li>
                        <li>
                            <a class="dropdown-item log-profile" href="{% url 'account:logout_user'%}">
                            Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </nav>

templates/navbar.html
<div class="col-md-3 my-profile-w-15">
    <div class="sticky-content">
        <div class="profile-nav">
            <div class="profile-navigation">
                <ul>
                    {% url 'management:user_dashboard' as user_dashboard_url %}
                    <li {% if request.path == user_dashboard_url %} class="active" {% endif %}><a href="{% url 'management:user_dashboard' %}"><span class="material-symbols-rounded me-2">
                        grid_view
                        </span>Dashboard</a></li>
                        {% if request.user.role == 3%}
                        {% url 'management:create_complain' as create_complain_url %}
                        <li {% if request.path == create_complain_url %} class="active" {% endif %}><a href="{% url 'management:create_complain' %}"><span class="material-symbols-rounded me-2">
                        add_comment
                        </span>Register Enquiry</a></li>
                        {% endif %}
                        {% if request.user.role == 1%}
                        {% url 'management:anonymous_complain' as anonymous_complain_url %}
                        <li {% if request.path == anonymous_complain_url %} class="active" {% endif %}><a href="{% url 'management:anonymous_complain' %}"><span class="material-symbols-rounded me-2">
                            add_comment
                            </span>Register Enquiry</a></li>
                            {% endif %}
                            {% url 'management:all_complains' as all_complains_url %}
                            <li{% if request.path == all_complains_url %} class="active" {% endif %}><a href="{% url 'management:all_complains'%}"><span class="material-symbols-rounded me-2">
                        other_admission
                        </span>Enquiries</a></li>
                        {% url 'management:category_list' as category_list_url %}
                        <li {% if request.path == category_list_url %} class="active" {% endif %}><a href="{% url 'management:category_list'%}"><span class="material-symbols-rounded me-2">
                            category
                        </span>Categories</a></li>
                        {% if request.user.role == 1%}
                        {% url 'account:all_user' as all_user_url %}
                        <li {% if request.path == all_user_url %} class="active" {% endif %}><a href="{% url 'account:all_user' %}"><span class="material-symbols-rounded me-2">
                        group
                        </span>Users</a></li>
                        {% endif %}
                        {% if request.user.role == 1%}
                        {% url 'management:all_faqs' as all_faqs_url %}
                        <li {% if request.path == all_faqs_url %} class="active" {% endif %}><a href="{% url 'management:all_faqs' %}"><span class="material-symbols-rounded me-2">
                            group
                            </span>FAQs</a></li>
                            {% endif %}
                            {% url 'account:change_password' as change_password_url %}
                            <li {% if request.path == change_password_url %} class="active" {% endif %}><a href="{% url 'account:change_password' %}"><span class="material-symbols-rounded me-2">
                        lock_reset
                        </span>Change Password</a></li>
                        {% url 'account:logout_user' as logout_user_url %}
                        <li {% if request.path == logout_user_url %} class="active" {% endif %}><a href="{% url 'account:logout_user'%}"><span class="material-symbols-rounded me-2">
                        logout
                        </span>Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>